create or replace function public.recalculate_instrument (
  p_user_id       uuid,
  p_instrument_id bigint
)
  returns void
  language plpgsql
  AS $function$
declare
    v_transaction record;

    v_units numeric := 0;
    v_avg_buy_cost numeric := 0;
    v_realized_pl numeric := 0;

    v_new_shares numeric;
    v_new_units numeric;
    v_new_avg_buy_cost numeric;
    v_transaction_realized_pl numeric;
begin

    -- ========================================================
    -- RESET INSTRUMENT STATE
    -- ========================================================

    v_units := 0;
    v_avg_buy_cost := 0;
    v_realized_pl := 0;


    -- ========================================================
    -- REPLAY ALL TRANSACTIONS IN CHRONOLOGICAL ORDER
    -- ========================================================

    for v_transaction in
        select
            id,
            action,
            units,
            price,
            dividend_cash,
            dividend_shares_ratio
        from public.transactions
        where user_id = p_user_id
          and instrument_id = p_instrument_id
        order by txn_date asc, id asc
    loop

        -- ====================================================
        -- BUY
        -- ====================================================

        if v_transaction.action = 'Buy' then

            v_units :=
                v_units + v_transaction.units;

            v_avg_buy_cost :=
                (
                    (v_units - v_transaction.units) * v_avg_buy_cost
                    + (v_transaction.units * v_transaction.price)
                )
                / v_units;

            -- Buy has no realized P/L
            update public.transactions
            set realized_pl = 0
            where id = v_transaction.id;


        -- ====================================================
        -- SELL
        -- ====================================================

        elsif v_transaction.action = 'Sell' then

            -- The edited history may make a later sell invalid
            if v_transaction.units > v_units then
                raise exception
                    'Insufficient units for transaction %',
                    v_transaction.id;
            end if;

            v_transaction_realized_pl :=
                v_transaction.units
                * (v_transaction.price - v_avg_buy_cost);

            v_units :=
                v_units - v_transaction.units;

            if v_units = 0 then
                v_avg_buy_cost := 0;
            end if;

            v_realized_pl :=
                v_realized_pl + v_transaction_realized_pl;

            -- Update the realized P/L generated by THIS sell
            update public.transactions
            set realized_pl = v_transaction_realized_pl
            where id = v_transaction.id;


        -- ====================================================
        -- DIVIDEND CASH
        -- ====================================================

        elsif v_transaction.action = 'Dividend Cash' then

            v_realized_pl :=
                v_realized_pl + v_transaction.dividend_cash;

            update public.transactions
            set realized_pl = v_transaction.dividend_cash
            where id = v_transaction.id;


        -- ====================================================
        -- DIVIDEND SHARES
        -- ====================================================

        elsif v_transaction.action = 'Dividend Shares' then

            if v_units <= 0 then
                raise exception
                    'No units available for dividend shares transaction %',
                    v_transaction.id;
            end if;

            v_new_shares :=
                v_units * v_transaction.dividend_shares_ratio;

            v_new_units :=
                v_units + v_new_shares;

            -- Total cost basis stays the same
            v_new_avg_buy_cost :=
                (v_units * v_avg_buy_cost)
                / v_new_units;

            v_units := v_new_units;
            v_avg_buy_cost := v_new_avg_buy_cost;

            update public.transactions
            set realized_pl = 0
            where id = v_transaction.id;

        end if;

    end loop;


    -- ========================================================
    -- UPDATE INSTRUMENT SUMMARY
    -- ========================================================

    update public.instruments
    set
        units_held = v_units,
        avg_buy_cost = v_avg_buy_cost,
        realized_pl = v_realized_pl
    where id = p_instrument_id
      and user_id = p_user_id;

end;
$function$;