-- ============================================================
-- REPLAY / RECALCULATE INSTRUMENT
-- ============================================================

create or replace function public.recalculate_instrument(
    p_user_id uuid,
    p_instrument_id bigint
)
returns void
language plpgsql
security invoker
as $$
declare
    v_transaction record;

    v_units numeric := 0;
    v_avg_buy_cost numeric := 0;
    v_realized_pl numeric := 0;

    v_new_shares numeric;
    v_new_units numeric;
    v_new_avg_buy_cost numeric;
    v_transaction_realized_pl numeric;
begin

    -- ========================================================
    -- RESET INSTRUMENT STATE
    -- ========================================================

    v_units := 0;
    v_avg_buy_cost := 0;
    v_realized_pl := 0;


    -- ========================================================
    -- REPLAY ALL TRANSACTIONS IN CHRONOLOGICAL ORDER
    -- ========================================================

    for v_transaction in
        select
            id,
            action,
            units,
            price,
            dividend_cash,
            dividend_shares_ratio
        from public.transactions
        where user_id = p_user_id
          and instrument_id = p_instrument_id
        order by txn_date asc, id asc
    loop

        -- ====================================================
        -- BUY
        -- ====================================================

        if v_transaction.action = 'Buy' then

            v_units :=
                v_units + v_transaction.units;

            v_avg_buy_cost :=
                (
                    (v_units - v_transaction.units) * v_avg_buy_cost
                    + (v_transaction.units * v_transaction.price)
                )
                / v_units;

            -- Buy has no realized P/L
            update public.transactions
            set realized_pl = 0
            where id = v_transaction.id;


        -- ====================================================
        -- SELL
        -- ====================================================

        elsif v_transaction.action = 'Sell' then

            -- The edited history may make a later sell invalid
            if v_transaction.units > v_units then
                raise exception
                    'Insufficient units for transaction %',
                    v_transaction.id;
            end if;

            v_transaction_realized_pl :=
                v_transaction.units
                * (v_transaction.price - v_avg_buy_cost);

            v_units :=
                v_units - v_transaction.units;

            if v_units = 0 then
                v_avg_buy_cost := 0;
            end if;

            v_realized_pl :=
                v_realized_pl + v_transaction_realized_pl;

            -- Update the realized P/L generated by THIS sell
            update public.transactions
            set realized_pl = v_transaction_realized_pl
            where id = v_transaction.id;


        -- ====================================================
        -- DIVIDEND CASH
        -- ====================================================

        elsif v_transaction.action = 'Dividend Cash' then

            v_realized_pl :=
                v_realized_pl + v_transaction.dividend_cash;

            update public.transactions
            set realized_pl = v_transaction.dividend_cash
            where id = v_transaction.id;


        -- ====================================================
        -- DIVIDEND SHARES
        -- ====================================================

        elsif v_transaction.action = 'Dividend Shares' then

            if v_units <= 0 then
                raise exception
                    'No units available for dividend shares transaction %',
                    v_transaction.id;
            end if;

            v_new_shares :=
                v_units * v_transaction.dividend_shares_ratio;

            v_new_units :=
                v_units + v_new_shares;

            -- Total cost basis stays the same
            v_new_avg_buy_cost :=
                (v_units * v_avg_buy_cost)
                / v_new_units;

            v_units := v_new_units;
            v_avg_buy_cost := v_new_avg_buy_cost;

            update public.transactions
            set realized_pl = 0
            where id = v_transaction.id;

        end if;

    end loop;


    -- ========================================================
    -- UPDATE INSTRUMENT SUMMARY
    -- ========================================================

    update public.instruments
    set
        units_held = v_units,
        avg_buy_cost = v_avg_buy_cost,
        realized_pl = v_realized_pl
    where id = p_instrument_id
      and user_id = p_user_id;

end;
$$;


-- ============================================================
-- UPDATE TRANSACTION
-- ============================================================

create or replace function public.update_transaction(
    p_user_id uuid,
    p_transaction_id bigint,
    p_instrument_id bigint,
    p_action text,
    p_units numeric,
    p_price numeric,
    p_dividend_cash numeric,
    p_dividend_shares_ratio numeric,
    p_txn_date date
)
returns void
language plpgsql
security invoker
as $$
declare
    v_old_instrument_id bigint;
    v_locked_instrument_id bigint;
begin

    -- ========================================================
    -- LOCK TRANSACTION
    -- ========================================================

    select instrument_id
    into v_old_instrument_id
    from public.transactions
    where id = p_transaction_id
      and user_id = p_user_id
    for update;

    if not found then
        raise exception 'Transaction not found';
    end if;


    -- ========================================================
    -- LOCK OLD INSTRUMENT
    -- ========================================================

    select id
    into v_locked_instrument_id
    from public.instruments
    where id = v_old_instrument_id
      and user_id = p_user_id
    for update;

    if not found then
        raise exception 'Old instrument not found';
    end if;


    -- ========================================================
    -- LOCK NEW INSTRUMENT
    -- ========================================================
    -- Only needed if the transaction is being moved
    -- to another instrument.

    if p_instrument_id <> v_old_instrument_id then

        select id
        into v_locked_instrument_id
        from public.instruments
        where id = p_instrument_id
          and user_id = p_user_id
        for update;

        if not found then
            raise exception 'New instrument not found';
        end if;

    end if;


    -- ========================================================
    -- UPDATE TRANSACTION
    -- ========================================================

    update public.transactions
    set
        instrument_id = p_instrument_id,
        action = p_action,
        units = p_units,
        price = p_price,
        dividend_cash = p_dividend_cash,
        dividend_shares_ratio = p_dividend_shares_ratio,
        txn_date = p_txn_date
    where id = p_transaction_id
      and user_id = p_user_id;


    -- ========================================================
    -- REPLAY
    -- ========================================================

    if p_instrument_id = v_old_instrument_id then

        -- Same instrument → replay once
        perform public.recalculate_instrument(
            p_user_id,
            v_old_instrument_id
        );

    else

        -- Different instruments → replay both

        -- Old instrument loses the transaction
        perform public.recalculate_instrument(
            p_user_id,
            v_old_instrument_id
        );

        -- New instrument receives the transaction
        perform public.recalculate_instrument(
            p_user_id,
            p_instrument_id
        );

    end if;

end;
$$;


-- ============================================================
-- DELETE TRANSACTION
-- ============================================================

create or replace function public.delete_transaction(
    p_user_id uuid,
    p_transaction_id bigint
)
returns void
language plpgsql
security invoker
as $$
declare
    v_instrument_id bigint;
    v_locked_instrument_id bigint;
begin

    -- ========================================================
    -- LOCK TRANSACTION
    -- ========================================================

    select instrument_id
    into v_instrument_id
    from public.transactions
    where id = p_transaction_id
      and user_id = p_user_id
    for update;

    if not found then
        raise exception 'Transaction not found';
    end if;


    -- ========================================================
    -- LOCK INSTRUMENT
    -- ========================================================

    select id
    into v_locked_instrument_id
    from public.instruments
    where id = v_instrument_id
      and user_id = p_user_id
    for update;

    if not found then
        raise exception 'Instrument not found';
    end if;


    -- ========================================================
    -- DELETE TRANSACTION
    -- ========================================================

    delete from public.transactions
    where id = p_transaction_id
      and user_id = p_user_id;


    -- ========================================================
    -- REPLAY REMAINING TRANSACTIONS
    -- ========================================================

    perform public.recalculate_instrument(
        p_user_id,
        v_instrument_id
    );

end;
$$;