-- ============================================================
-- Add transaction-level realized P/L
-- ============================================================

alter table public.transactions
add column realized_pl numeric not null default 0;


-- ============================================================
-- Reset existing test data
-- ============================================================

delete from public.transactions;
delete from public.instruments;


-- ============================================================
-- BUY TRANSACTION
-- ============================================================

create or replace function public.create_buy_transaction(
    p_user_id uuid,
    p_instrument_id bigint,
    p_units numeric,
    p_price numeric,
    p_txn_date date
)
returns void
language plpgsql
security invoker
as $$
declare
    v_old_units numeric;
    v_old_avg_buy_cost numeric;
    v_new_units numeric;
    v_new_avg_buy_cost numeric;
begin

    -- Validate input
    if p_units <= 0 then
        raise exception 'Units must be greater than zero';
    end if;

    if p_price <= 0 then
        raise exception 'Price must be greater than zero';
    end if;

    -- Get the instrument and lock its row
    select
        units_held,
        avg_buy_cost
    into
        v_old_units,
        v_old_avg_buy_cost
    from public.instruments
    where id = p_instrument_id
      and user_id = p_user_id
    for update;

    -- Make sure the instrument exists and belongs to the user
    if not found then
        raise exception 'Instrument not found';
    end if;

    -- Calculate new number of units
    v_new_units := v_old_units + p_units;

    -- Calculate new weighted average buy cost
    v_new_avg_buy_cost :=
        (
            (v_old_units * v_old_avg_buy_cost)
            + (p_units * p_price)
        )
        / v_new_units;

    -- Insert transaction
    insert into public.transactions (
        user_id,
        instrument_id,
        action,
        txn_date,
        units,
        price,
        realized_pl
    )
    values (
        p_user_id,
        p_instrument_id,
        'Buy',
        p_txn_date,
        p_units,
        p_price,
        0
    );

    -- Update instrument summary
    update public.instruments
    set
        units_held = v_new_units,
        avg_buy_cost = v_new_avg_buy_cost
    where id = p_instrument_id
      and user_id = p_user_id;

end;
$$;


-- ============================================================
-- SELL TRANSACTION
-- ============================================================

create or replace function public.create_sell_transaction(
    p_user_id uuid,
    p_instrument_id bigint,
    p_units numeric,
    p_price numeric,
    p_txn_date date
)
returns void
language plpgsql
security invoker
as $$
declare
    v_old_units numeric;
    v_avg_buy_cost numeric;
    v_old_realized_pl numeric;
    v_new_units numeric;

    -- Realized P/L generated by THIS sell transaction
    v_transaction_realized_pl numeric;

    -- New cumulative realized P/L on the instrument
    v_new_realized_pl numeric;
begin

    -- Validate input
    if p_units <= 0 then
        raise exception 'Units must be greater than zero';
    end if;

    if p_price <= 0 then
        raise exception 'Price must be greater than zero';
    end if;

    -- Get the instrument and lock its row
    select
        units_held,
        avg_buy_cost,
        realized_pl
    into
        v_old_units,
        v_avg_buy_cost,
        v_old_realized_pl
    from public.instruments
    where id = p_instrument_id
      and user_id = p_user_id
    for update;

    -- Make sure the instrument exists and belongs to the user
    if not found then
        raise exception 'Instrument not found';
    end if;

    -- Make sure the user owns enough units
    if p_units > v_old_units then
        raise exception 'Insufficient units to sell';
    end if;

    -- Calculate new units
    v_new_units := v_old_units - p_units;

    -- Calculate realized P/L generated by THIS transaction
    v_transaction_realized_pl :=
        p_units * (p_price - v_avg_buy_cost);

    -- Calculate new cumulative instrument realized P/L
    v_new_realized_pl :=
        v_old_realized_pl + v_transaction_realized_pl;

    -- Insert transaction
    insert into public.transactions (
        user_id,
        instrument_id,
        action,
        txn_date,
        units,
        price,
        realized_pl
    )
    values (
        p_user_id,
        p_instrument_id,
        'Sell',
        p_txn_date,
        p_units,
        p_price,
        v_transaction_realized_pl
    );

    -- Update instrument summary
    update public.instruments
    set
        units_held = v_new_units,

        avg_buy_cost = case
            when v_new_units = 0 then 0
            else v_avg_buy_cost
        end,

        realized_pl = v_new_realized_pl

    where id = p_instrument_id
      and user_id = p_user_id;

end;
$$;


-- ============================================================
-- DIVIDEND CASH TRANSACTION
-- ============================================================

create or replace function public.create_dividend_cash_transaction(
    p_user_id uuid,
    p_instrument_id bigint,
    p_dividend_cash numeric,
    p_txn_date date
)
returns void
language plpgsql
security invoker
as $$
declare
    v_old_realized_pl numeric;
begin

    -- Validate input
    if p_dividend_cash <= 0 then
        raise exception 'Dividend cash must be greater than zero';
    end if;

    -- Get the current realized P/L and lock the instrument row
    select
        realized_pl
    into
        v_old_realized_pl
    from public.instruments
    where id = p_instrument_id
      and user_id = p_user_id
    for update;

    -- Make sure the instrument exists and belongs to the user
    if not found then
        raise exception 'Instrument not found';
    end if;

    -- Insert the dividend cash transaction
    insert into public.transactions (
        user_id,
        instrument_id,
        action,
        txn_date,
        dividend_cash,
        realized_pl
    )
    values (
        p_user_id,
        p_instrument_id,
        'Dividend Cash',
        p_txn_date,
        p_dividend_cash,
        p_dividend_cash
    );

    -- Add dividend cash to instrument realized P/L
    update public.instruments
    set
        realized_pl = v_old_realized_pl + p_dividend_cash
    where id = p_instrument_id
      and user_id = p_user_id;

end;
$$;


-- ============================================================
-- DIVIDEND SHARES TRANSACTION
-- ============================================================

create or replace function public.create_dividend_shares_transaction(
    p_user_id uuid,
    p_instrument_id bigint,
    p_dividend_shares_ratio numeric,
    p_txn_date date
)
returns void
language plpgsql
security invoker
as $$
declare
    v_old_units numeric;
    v_old_avg_buy_cost numeric;
    v_new_units numeric;
    v_new_avg_buy_cost numeric;
    v_new_shares numeric;
begin

    -- Validate input
    if p_dividend_shares_ratio <= 0 then
        raise exception 'Dividend shares ratio must be greater than zero';
    end if;

    -- Get the current instrument values and lock the row
    select
        units_held,
        avg_buy_cost
    into
        v_old_units,
        v_old_avg_buy_cost
    from public.instruments
    where id = p_instrument_id
      and user_id = p_user_id
    for update;

    -- Make sure the instrument exists and belongs to the user
    if not found then
        raise exception 'Instrument not found';
    end if;

    -- Make sure the user currently owns units
    if v_old_units <= 0 then
        raise exception 'No units available for dividend shares';
    end if;

    -- Calculate the number of free shares received
    v_new_shares :=
        v_old_units * p_dividend_shares_ratio;

    -- Calculate the new total units
    v_new_units :=
        v_old_units + v_new_shares;

    -- Calculate the new average buy cost
    -- Total cost basis stays unchanged while units increase
    v_new_avg_buy_cost :=
        (v_old_units * v_old_avg_buy_cost)
        / v_new_units;

    -- Insert dividend shares transaction
    insert into public.transactions (
        user_id,
        instrument_id,
        action,
        txn_date,
        dividend_shares_ratio,
        realized_pl
    )
    values (
        p_user_id,
        p_instrument_id,
        'Dividend Shares',
        p_txn_date,
        p_dividend_shares_ratio,
        0
    );

    -- Update instrument summary
    update public.instruments
    set
        units_held = v_new_units,
        avg_buy_cost = v_new_avg_buy_cost
    where id = p_instrument_id
      and user_id = p_user_id;

end;
$$;
